# Generated by Django 3.1.7 on 2021-09-11 23:13

import cadastros.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('telefone', models.IntegerField()),
                ('foto', models.ImageField(blank=True, default='', null=True, upload_to=cadastros.models.foto)),
                ('url_foto', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('nome', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.BooleanField()),
                ('encerramento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rachas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=cadastros.models.imagem)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('gol_score', models.CharField(blank=True, max_length=10, null=True)),
                ('assistencia_score', models.CharField(blank=True, max_length=10, null=True)),
                ('presenca_score', models.CharField(blank=True, max_length=10, null=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField(blank=True, null=True)),
                ('assistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.jogadores')),
                ('gol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_gol', to='cadastros.jogadores')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('score', models.FloatField(blank=True, default=0.0, null=True)),
                ('sigla', models.CharField(blank=True, max_length=5, null=True)),
                ('contabilizar_no_geral', models.BooleanField(default=False)),
                ('racha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.rachas')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='racha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.rachas'),
        ),
        migrations.CreateModel(
            name='JogadoresPartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.jogadores')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.partida')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoPremio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.jogadores')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.partida')),
                ('premio_racha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.premios')),
            ],
            options={
                'unique_together': {('jogador', 'premio_racha', 'partida')},
            },
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.candidatopremio')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.jogadores')),
            ],
            options={
                'unique_together': {('candidato', 'eleitor')},
            },
        ),
        migrations.CreateModel(
            name='PremioPartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.jogadores')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.partida')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.premios')),
            ],
            options={
                'unique_together': {('jogador', 'premio', 'partida')},
            },
        ),
        migrations.CreateModel(
            name='JogadoresRacha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.jogadores')),
                ('racha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.rachas')),
            ],
            options={
                'ordering': ['jogador'],
                'unique_together': {('jogador', 'racha')},
            },
        ),
    ]
