# Generated by Django 3.1.7 on 2023-01-21 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0002_rachas_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogadores',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='jogador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Mensalidade'), ('2', 'Outro')], max_length=100)),
                ('entrada', models.CharField(choices=[('1', 'RECEITA'), ('2', 'DESPESA')], max_length=100)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateField()),
                ('pagante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.jogadoresracha')),
                ('racha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.rachas')),
            ],
        ),
    ]
