# Generated by Django 2.1.5 on 2019-01-09 03:20

import cadastros.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('foto', models.ImageField(blank=True, default='', null=True, upload_to=cadastros.models.foto)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JogadoresPartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Jogadores')),
            ],
        ),
        migrations.CreateModel(
            name='JogadoresRacha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Jogadores')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PremioPartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Jogadores')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Partida')),
            ],
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('score', models.FloatField(blank=True, default=0.0, null=True)),
                ('sigla', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rachas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=cadastros.models.imagem)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField(blank=True, null=True)),
                ('assistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Jogadores')),
                ('gol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_gol', to='cadastros.Jogadores')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Partida')),
            ],
        ),
        migrations.AddField(
            model_name='premios',
            name='racha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Rachas'),
        ),
        migrations.AddField(
            model_name='premiopartida',
            name='premio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Premios'),
        ),
        migrations.AddField(
            model_name='partida',
            name='racha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Rachas'),
        ),
        migrations.AddField(
            model_name='jogadoresracha',
            name='racha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Rachas'),
        ),
        migrations.AddField(
            model_name='jogadorespartida',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Partida'),
        ),
    ]
