# Generated by Django 2.1.5 on 2020-10-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20201010_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadores',
            name='url_foto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jogadores',
            name='nome',
            field=models.CharField(max_length=250),
        ),
    ]
