# Generated by Django 2.1.5 on 2020-10-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20201011_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='rachas',
            name='assistencia_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rachas',
            name='gol_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogadores',
            name='telefone',
            field=models.IntegerField(max_length=20),
        ),
    ]
