# Generated by Django 2.1.5 on 2020-10-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20201011_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rachas',
            name='assistencia_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rachas',
            name='gol_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
