# Generated by Django 2.1.5 on 2020-10-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20201011_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='premios',
            name='contabilizar_no_geral',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rachas',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
