# Generated by Django 3.1.7 on 2021-09-11 20:13

import cadastros.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20201012_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadorespartida',
            name='presente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partida',
            name='encerramento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rachas',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rachas',
            name='codigo',
            field=models.CharField(blank=True, default=cadastros.models.create_if_hash, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rachas',
            name='presenca_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jogadores',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='premios',
            name='sigla',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='rachas',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='premiopartida',
            unique_together={('jogador', 'premio', 'partida')},
        ),
        migrations.CreateModel(
            name='CandidatoPremio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.jogadores')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.partida')),
                ('premio_racha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.premios')),
            ],
            options={
                'unique_together': {('jogador', 'premio_racha', 'partida')},
            },
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.candidatopremio')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.jogadores')),
            ],
            options={
                'unique_together': {('candidato', 'eleitor')},
            },
        ),
    ]
