# Generated by Django 3.1.7 on 2021-09-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_rachas_codigo_do_racha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rachas',
            name='codigo_do_racha',
        ),
    ]
