# Generated by Django 3.1.7 on 2021-09-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_rachas_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rachas',
            name='codigo',
        ),
    ]
